default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_DEVELOPMENT_USERNAME'] %>
  password: <%= ENV['DATABASE_DEVELOPMENT_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT_NAME'] %>
  host: <%= ENV['DATABASE_DEVELOPMENT_HOST'] %>
  port: <%= ENV['DATABASE_DEVELOPMENT_PORT'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] %>
  host: <%= ENV['DATABASE_TEST_HOST'] %>
  port: <%= ENV['DATABASE_TEST_PORT'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DATABASE_PRODUCTION_NAME'] %>
  host: <%= ENV['DATABASE_PRODUCTION_HOST'] %>
  port: <%= ENV['DATABASE_PRODUCTION_PORT'] %>
  username: <%= ENV['DATABASE_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DATABASE_PRODUCTION_PASSWORD'] %>
